monitor_config:
  signficance_threshold: 0.05 
  bayes_factor_threshold: 5
  window_size: 100
  grace_period: 500
  reference_uncertainty: 1
generator_specification:
  num_samples: 100
  num_features: 10
  num_domains: 50
  num_models: 25
  max_mean: 100
  drift_step: 0.2
  max_std: 20
  estimate_uncertainty: 0.2
  estimate_error: 0.2
estimate_errors:
- 0.01
- 0.05
- 0.1
- 0.15
- 0.2
- 0.25
- 0.3
estimate_uncertainties:
- 0.01
- 0.05
- 0.1
- 0.15
- 0.2
- 0.25
- 0.3
filename:
  experiment_A04_results
iterations: 30
rng: 42
threads: 10